version: '3.6'

volumes:
  composer-cache:

services:
  testbench:
    image: public.ecr.aws/cldevops/laravel:8.0-dev
    working_dir: /app
    volumes:
      - ./:/app
      - composer-cache:/root/.composer/cache
    command: phpunit
    extra_hosts:
      # set host=host.docker.internal in .env on linux for xdebug
      - ${host:-host}:host-gateway
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 start_with_request=yes log_level=0
      PHP_IDE_CONFIG: serverName=testbench
      XDEBUG_SESSION: testbench
      XDEBUG_MODE: debug
      APP_ENV: http://testbench
    ports:
      - "8080:80"
      - "8000"
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    shm_size: '2gb'
    ports:
      - "4444:4444"
      - "7900:7900"
